backend:
  name: git-gateway

media_folder: "hugo/static/assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Home" 
        name: "home"
        fields:
          - {label: "Tagline", name: "tagline", widget: "markdown"}
          - {label: "Call out cards", name: "card", widget: "object", fields: [
              {label: "Title One", name: "titleone", widget: "string"},
              {label: "Text One", name: "textone", widget: "markdown"},
              {label: "Title Two", name: "titletwo", widget: "string"},
              {label: "Text Two", name: "texttwo", widget: "markdown"},
              {label: "Title Three", name: "titlethree", widget: "string"},
              {label: "Text Three", name: "textthree", widget: "markdown"}
          ]}
          - {label: "Secondary call outs", name: "secondary", widget: "object", fields: [
              {label: "First", name: "callone", widget: "string"},
              {label: "Second", name: "calltwo", widget: "string"},
              {label: "Third", name: "callthree", widget: "string"},
          ]}
      - file: "content/content-page/_index.md"
        label: "Content page one"
        name: "content-page-one"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "markdown"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Highlight box", name: "highlight", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
