  
backend:
  name: git-gateway
  branch: master

media_folder: "/static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Home" 
        name: "home"
        fields:
          - {label: "Image", name: "img", widget: "image"}
          - {label: "Banner", name: "banner", widget: "object", fields: [
              {label: "Banner heading", name: "bannerHeading", widget: "string"},
              {label: "Banner copy", name: bannerCopy, widget: "markdown"}
            ]}
          - {label: "Tagline", name: "tagline", widget: "markdown"}
          - {label: "CTA cards", name: "ctaCards", widget: "object", fields: [
              {label: "Card one", name: "cardOne", widget: "object", fields: [
                {label: "Card title", name: "cardTitle", widget: "string"},
                {label: "Card text", name: "cardText", widget: "string"},
                {label: "Card link", name: "cardLink", widget: "string"}
              ]},
              {label: "Card two", name: "cardTwo", widget: "object", fields: [
                {label: "Card title", name: "cardTitle", widget: "string"},
                {label: "Card text", name: "cardText", widget: "string"},
                {label: "Card link", name: "cardLink", widget: "string"}
              ]},
              {label: "Card three", name: "cardThree", widget: "object", fields: [
                {label: "Card title", name: "cardTitle", widget: "string"},
                {label: "Card text", name: "cardText", widget: "string"},
                {label: "Card link", name: "cardLink", widget: "string"}
              ]}
            ]}
          - {label: "Learn more", name: "secondary", widget: "object", fields: [
              {label: "Button one", name: "buttonOne", widget: "object", fields: [
                {label: "Button text", name: "buttonText", widget: "string"},
                {label: "Button link", name: "Link", widget: "string"}
              ]},
              {label: "Button two", name: "buttonTwo", widget: "object", fields: [
                {label: "Button text", name: "buttonText", widget: "string"},
                {label: "Button link", name: "Link", widget: "string"}
              ]},
              {label: "Button three", name: "buttonThree", widget: "object", fields: [
                {label: "Button text", name: "buttonText", widget: "string"},
                {label: "Button link", name: "Link", widget: "string"}
              ]}
            ]}
      - file: "content/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Page title", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
          ]}
          - {label: "What is the GMHAN?", name: "whatIs", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "How the board works", name: "howWorks", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Achieved so far", name: "whatHave", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Who is involved?", name: "whoIs", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Working on", name: "whatAre", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
      - file: "content/give/_index.md"
        label: "Give"
        name: "give"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Highlight box top", name: "highlightTop", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Highlight box left", name: "highlightLeft", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Highlight box right", name: "highlightRight", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
      - file: "content/get-involved/_index.md"
        label: "Get Involved"
        name: "get-involved"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Speak Up", name: "speakUp", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "body", name: "body", widget: "markdown"}
          ]}
      - file: "content/news-and-events/_index.md"
        label: "News and Events"
        name: "events"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown", required: false}
          ]}
      - file: "content/resources/_index.md"
        label: "Resources"
        name: "resources"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string", required: false},
              {label: "Body", name: "body", widget: "markdown", required: false}
          ]}
  - name: "resources"
    label: "Resource pages"
    editor:
      preview: false
    files:
      - file: "content/learn-lobby-deliver/_index.md"
        label: "Learn, Lobby & Deliver"
        name: "learn-lobby-deliver"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/prevention-strategy/_index.md"
        label: "GMCA Homelessness Prevention Strategy"
        name: "prevention-strategy"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/covid-response/_index.md"
        label: "Covid Response"
        name: "covid-response"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/employment-training-education/_index.md"
        label: "Employment, training & education"
        name: "employment-training-education"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/criminal-justice-system/_index.md"
        label: "Criminal Justice System"
        name: "criminal-justice-system"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/youth-homelessness/_index.md"
        label: "Youth Homelessness"
        name: "youth-homelessness"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/health-and-homelessness/_index.md"
        label: "Health & Homelessness"
        name: "health-and-homelessness"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/womens-homelessness/_index.md"
        label: "Women’s Experience of Homelessness"
        name: "womens-homelessness"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/the-network/_index.md"
        label: "From The Network"
        name: "the-network"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/greater-manchester/_index.md"
        label: "Greater Manchester"
        name: "greater-manchester"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
      - file: "content/external/_index.md"
        label: "External"
        name: "external"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown",}
          ]}
  - name: "news-and-events"
    label: "news/event"
    editor:
      preview: false
    folder: "/content/news-and-events"
    create: true
    filter: {field: "event", value: true}
    fields:
      - {label: "Event", name: "event", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Summary (Card displayed on news and events page)", name: "eventCard", widget: "object", fields: [
          {label: "Heading", name: "name", widget: "string", required: false},
          {label: "Sub-heading or Location", name: "location", widget: "string", required: false},
          {label: "Date/Author", name: "date", widget: "string", required: false}
        ]}
      - {label: "Content", name: "content", widget: "object", fields: [
          {label: "Heading", name: "heading", widget: "string", required: false},
          {label: "Body", name: "body", widget: "markdown", required: false},
          {label: "Image (Aspect 3by2 - 1080px by 720px)", name: "image", widget: "image", required: false}
        ]}