backend:
  name: git-gateway

media_folder: "hugo/static/assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Home" 
        name: "home"
        fields:
          - {label: "Tagline", name: "tagline", widget: "markdown"}
          - {label: "CTA cards", name: "ctaCards", widget: "object", fields: [
              {label: "Card one", name: "cardOne", widget: "object", fields: [
                {label: "Card title", name: "cardTitle", widget: "string"},
                {label: "Card text", name: "cardText", widget: "string"},
                {label: "Card link", name: "cardLink", widget: "string"}
              ]},
              {label: "Card two", name: "cardTwo", widget: "object", fields: [
                {label: "Card title", name: "cardTitle", widget: "string"},
                {label: "Card text", name: "cardText", widget: "string"},
                {label: "Card link", name: "cardLink", widget: "string"}
              ]},
              {label: "Card three", name: "cardThree", widget: "object", fields: [
                {label: "Card title", name: "cardTitle", widget: "string"},
                {label: "Card text", name: "cardText", widget: "string"},
                {label: "Card link", name: "cardLink", widget: "string"}
              ]}
            ]}
          - {label: "Secondary call outs", name: "secondary", widget: "object", fields: [
              {label: "Button one", name: "buttonOne", widget: "object", fields: [
                {label: "Button text", name: "buttonText", widget: "string"},
                {label: "Button link", name: "Link", widget: "string"}
              ]},
              {label: "Button two", name: "buttonTwo", widget: "object", fields: [
                {label: "Button text", name: "buttonText", widget: "string"},
                {label: "Button link", name: "Link", widget: "string"}
              ]},
              {label: "Button three", name: "buttonThree", widget: "object", fields: [
                {label: "Button text", name: "buttonText", widget: "string"},
                {label: "Button link", name: "Link", widget: "string"}
              ]}
            ]}
      - file: "content/content-page/_index.md"
        label: "Content page one"
        name: "content-page-one"
        fields:
          - {label: "Content", name: "content", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Highlight box top", name: "highlightTop", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Highlight box left", name: "highlightLeft", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
          - {label: "Highlight box right", name: "highlightRight", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
          ]}
